from django.urls import path, include
from rest_framework_simplejwt.views import TokenRefreshView
from rest_framework.routers import DefaultRouter
from .views import CreateAccountView, LoginView, LogoutView, ChangePasswordView, RoleViewSet, UsersViewSet, ChatViewSet

# Router configuration for viewsets (Role, Users, Chat)
router = DefaultRouter()
router.register(r'roles', RoleViewSet, basename='role')
router.register(r'users', UsersViewSet, basename='user')
router.register(r'chats', ChatViewSet, basename='chat')

# URL patterns for accounts app
urlpatterns = [
    path('create-account/', CreateAccountView.as_view(), name='create_account'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('change-password/', ChangePasswordView.as_view(), name='change_password'),
    path('token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),

    # Include the routes generated by the DefaultRouter
    path('', include(router.urls)),
]
