# Generated by Django 5.0.3 on 2024-10-13 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_present', models.BooleanField(default=False)),
                ('balcon', models.BooleanField(default=False)),
                ('is_meuble', models.BooleanField(default=False)),
                ('is_parking', models.BooleanField(default=False)),
                ('surface_balcon', models.FloatField(blank=True, null=True)),
                ('ascenseur', models.BooleanField(default=False)),
                ('terrasse', models.BooleanField(default=False)),
                ('jardin', models.BooleanField(default=False)),
                ('piscine', models.BooleanField(default=False)),
                ('route_pavee', models.BooleanField(default=False)),
                ('distance_route', models.FloatField(blank=True, null=True)),
                ('groupes_elec', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TypeLogement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TypePiece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Logement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edge_left', models.FloatField()),
                ('edge_right', models.FloatField()),
                ('dimension', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('id_position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logements.position')),
                ('id_type_logement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logements.typelogement')),
            ],
        ),
        migrations.CreateModel(
            name='Piece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.BinaryField()),
                ('montant_du_piece', models.FloatField()),
                ('dimension', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('id_condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logements.condition')),
                ('id_logement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logements.logement')),
                ('id_type_piece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logements.typepiece')),
            ],
        ),
    ]
